import type { NoodleBoss } from "./types";

export const NOODLE_BOSSES: NoodleBoss[] = [
  {
    id: "hongshao",
    name: "红烧牛肉面",
    title: "经典Boss",
    level: 7,
    toughness: 80,
    exp: 0,
    coolingFactor: 1,
    slurpFactor: 1,
    palette: {
      bowl: "#c0392b",
      bowlHi: "#e0594b",
      bowlShadow: "#8c1d18",
      band: "#ffd24a",
      bandHi: "#fff0bf",
      noodle: "#f2c64e",
      noodleHi: "#ffe07a",
      strand: "#d89a2a",
      meat: "#8c3a1e",
      accent: "#ffb43a",
      garnish: "#3f7a34",
    },
  },
  {
    id: "suancai",
    name: "酸菜牛肉面",
    title: "酸香军师",
    level: 8,
    toughness: 86,
    exp: 18,
    coolingFactor: 0.96,
    slurpFactor: 1.03,
    palette: {
      bowl: "#315f3e",
      bowlHi: "#4f8b56",
      bowlShadow: "#17351f",
      band: "#d5d66a",
      bandHi: "#f5f2b0",
      noodle: "#ead063",
      noodleHi: "#fff08a",
      strand: "#b99a2c",
      meat: "#7b4024",
      accent: "#a9c85f",
      garnish: "#77a43a",
    },
  },
  {
    id: "paojiao",
    name: "泡椒牛肉面",
    title: "泡椒先锋",
    level: 9,
    toughness: 90,
    exp: 32,
    coolingFactor: 0.92,
    slurpFactor: 0.98,
    palette: {
      bowl: "#d6632f",
      bowlHi: "#f28c38",
      bowlShadow: "#8d2d17",
      band: "#91d14f",
      bandHi: "#d5ff8a",
      noodle: "#f1cb55",
      noodleHi: "#ffe98a",
      strand: "#d39028",
      meat: "#8d3d20",
      accent: "#9bd84d",
      garnish: "#3f8e32",
    },
  },
  {
    id: "xiangla",
    name: "香辣牛肉面",
    title: "红油猛将",
    level: 9,
    toughness: 88,
    exp: 28,
    coolingFactor: 0.9,
    slurpFactor: 1.02,
    palette: {
      bowl: "#9f1f20",
      bowlHi: "#d93b2e",
      bowlShadow: "#5d1114",
      band: "#ffbf3b",
      bandHi: "#ffed9a",
      noodle: "#efbd4c",
      noodleHi: "#ffd96d",
      strand: "#c76b22",
      meat: "#6f2f1a",
      accent: "#ff5d33",
      garnish: "#469442",
    },
  },
  {
    id: "laotan",
    name: "老坛酸菜面",
    title: "坛中魔王",
    level: 10,
    toughness: 95,
    exp: 48,
    coolingFactor: 0.86,
    slurpFactor: 0.95,
    palette: {
      bowl: "#4c4b2b",
      bowlHi: "#77713e",
      bowlShadow: "#242315",
      band: "#b6c45f",
      bandHi: "#e6e99f",
      noodle: "#e2c45f",
      noodleHi: "#fff09b",
      strand: "#a98935",
      meat: "#6a3f25",
      accent: "#cbd46d",
      garnish: "#6c9a39",
    },
  },
];

export const DEFAULT_NOODLE_BOSS = NOODLE_BOSSES[0];

export function findNoodleBoss(id: string) {
  return NOODLE_BOSSES.find((boss) => boss.id === id) ?? DEFAULT_NOODLE_BOSS;
}
